---
- name: setup
  hosts: all
  tasks:
    - include: tasks/yadm.yml
    - include: tasks/utils.yml
    - include: tasks/python.yml
    - include: tasks/shell.yml
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: "{{ lookup('env', 'HOME') }}"
    yadm:
      repo: git@github.com:mskrajnowski/dotfiles.git
  vars_files:
    - vars.yml
