---
- name: check ubuntu version
  command: lsb_release -cs
  register: ubuntu_version
- name: add docker repo key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
  become: true
- name: add docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout_lines[0] }} stable
    filename: docker
  become: true
- name: install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  become: true
- name: install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
  become: true
- name: add docker group
  group:
    name: docker
  become: true
- name: add {{ user }} to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: true
  become: true
