---
- name: add Visual Studio Code repository
  apt_repository: 
    repo: deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
  become: true
- name: install Visual Studio Code
  apt:
    name: code
  become: true
- name: install Visual Studio Code extensions
  command: "{{ home | quote }}/.yadm/vscode/restore"
