---
- name: add google repo key
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  become: true
- name: add google chrome repo
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    update_cache: true
  become: true
- name: install google chrome
  apt:
    name: google-chrome-stable
  become: true
