---
- name: install python
  apt:
    name:
      - python-dev
      - python-pip
      - python3-dev
      - python3-pip
  become: true
- name: install pipenv
  command: pip3 install --user pipenv
  args:
    creates: "{{ home | quote }}/.local/bin/pipenv"
- name: install nodejs
  apt:
    name:
      - nodejs
      - npm
  become: true
- name: install latest npm
  command: npm install -g npm
  args:
    creates: /usr/local/bin/npm
  become: true
- name: install plop
  command: npm install -g plop
  args:
    creates: /usr/local/bin/plop
  become: true
- name: install go
  apt:
    name:
      - golang-go
      - go-dep
  become: true
