---
- name: install essential utilities
  apt:
    name: 
      - aptitude
      - build-essential
      - curl
      - htop
      - tig
      - httpie
      - tmuxinator
      - nnn
  become: true
    
