---
- name: add enpass repo key
  apt_key:
    url: https://apt.enpass.io/keys/enpass-linux.key
  become: true
- name: add enpass repo
  apt_repository:
    repo: deb https://apt.enpass.io/ stable main
  become: true
- name: install essential utilities
  apt:
    name:
      - aptitude
      - build-essential
      - curl
      - htop
      - tig
      - httpie
      - tmuxinator
      - nnn
      - enpass
      - tilix
      - peek
  become: true
