---
- name: install essential utilities
  apt:
    name: "{{ item }}"
  become: true
  with_items:
    - aptitude
    - build-essential
    - curl
    - htop
    - tig
    - httpie
    - tmuxinator
    - nnn
